export type btnClassType =
  | 'btn-big'
  | 'btn-big btn-secondary'
  | 'btn-big btn-light'
  | 'btn-small'
  | 'btn-small btn-secondary'
  | 'btn-small btn-light'
  | 'btn-tiny'
  | 'btn-tiny btn-secondary'
  | 'btn-tiny btn-light'

export type titleType =
  | 'Big Primary Buttons'
  | 'Big Secondary Buttons'
  | 'Big Light Buttons'
  | 'Small Primary Buttons'
  | 'Small Secondary Buttons'
  | 'Small Light Buttons'
  | 'Tiny Primary Buttons'
  | 'Tiny Secondary Buttons'
  | 'Tiny Light Buttons'
