name: Auto Release
on:
  workflow_run:
    workflows: ["Run Unit Tests and Lint Files"]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get version from package.json
        id: pkg
        run: echo "::set-output name=version::$(node -p "require('./../package.json').version")"
      - name: Prepare new version
        id: prepare_version
        uses: actions/github-script@v5
        with:
          script: |
            const version = "${{ steps.pkg.outputs.version }}";
            const [major, minor, patch] = version.split('.');
            const newVersion = `${major}.${minor}.${parseInt(patch) + 1}`;
            return newVersion.replace(/"/g, '');
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.prepare_version.outputs.result }}
          release_name: ${{ steps.prepare_version.outputs.result }}
          draft: false
          prerelease: false
