name: Auto Release
on:
  workflow_run:
    workflows: ["Run Unit Tests and Lint Files"]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get latest tag
        id: latesttag
        uses: actions/github-script@v5
        with:
          script: |
            const githubV = require('@actions/github');
            const octokit = githubV.getOctokit(process.env.GITHUB_TOKEN);
            const tags = await octokit.repos.listTags({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            const latestTag = tags.data[0].name;
            const [version, preRelease] = latestTag.substring(1).split('-'); // remove the 'v' prefix and split version and pre-release
            const [major, minor, patch] = version.split('.');
            const newVersion = `${major}.${minor}.${parseInt(patch) + 1}`;
            return `v${newVersion}-${preRelease}`;
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.latesttag.outputs.result }}
          release_name: Release ${{ steps.latesttag.outputs.result }}
          draft: false
          prerelease: false
